version: "3.6"
services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - monitoring
    volumes:
      - grafana-volume:/var/lib/grafana
  
  influxdb:
    image: influxdb
    restart: always
    ports:
      - 8086:8086
    environment:
        - INFLUXDB_DB=telegraf
        - INFLUXDB_ADMIN_USER=admin
        - INFLUXDB_ADMIN_PASSWORD=theadminpapssword
        - INFLUXDB_USER=luko
        - INFLUXDB_PASSWORD=thelukopassword
    networks:
      - monitoring
    volumes:
      - influxdb-volume:/var/lib/influxdb
networks:
  monitoring:
volumes:
  grafana-volume:
    external: true
  influxdb-volume:
    external: true
