version: "3.6"
services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - monitoring
    volumes:
      - grafana-volume:/var/lib/grafana
  
  influxdb:
    image: influxdb
    restart: always
    ports:
      - 8086:8086
    environment:
        - INFLUXDB_DB=telegraf
        - INFLUXDB_HTTP_AUTH_ENABLED=True
        - INFLUXDB_ADMIN_USER=admin
        - INFLUXDB_ADMIN_PASSWORD=theadminpassword
        - INFLUXDB_USER=luko
        - INFLUXDB_PASSWORD=thelukopassword
    networks:
      - monitoring
    volumes:
      - influxdb-volume:/var/lib/influxdb
    command:
      - influxd
networks:
  monitoring:
volumes:
  grafana-volume:
  influxdb-volume:
